### ISSUE TITLE
sudo python3 install.py fails

### ISSUE THREAD

**Issue by jooprzol** [timothybrown/BSEC-Conduit#3]
I get the following when I run sudo python3 install.py:

****************************************************************************
************************** BSEC-Conduit Installer **************************
****************************************************************************

  Install Location: /opt/bsec
  Press CTRL-C to abort. Starting in 1...

 Bosch Sensortec Environmental Cluster (BSEC) Setup
Traceback (most recent call last):ive...
  File "install.py", line 43, in <module>
    with urllib.request.urlopen('{}/{}.zip'.format(bsec_url, bsec_ver)) as response, open(bsec_zip, 'wb') as out_file:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

---------------------------

The previous commands seemed to go through properly. Anything I need to double check?
Thanks

**Comment by jooprzol** [comment]
got past the issue,  updates bsec_ver to the latest version on bosch's website: BSEC_1.4.7.3_Generic_Release_20190410
